### ISSUE TITLE
Error message on install

### ISSUE THREAD

**Issue by ediooo** [sudosilico/sample-diffusion#6]
Hi,
When I try to install on OSX 10.15.7 I get this:

conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - cudatoolkit=11.3

Any idea what I need to do?

Thank you!

**Comment by ediooo** [comment]
I tried installing it using this command: 
conda install -c anaconda cudatoolkit
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


So it seems to be there, but would I have to install 11.3 specifically and if so, how would I do that?

**Comment by sudosilico** [comment]
I don't believe CUDA is supported on MacOS. I'm guessing that installing it without the fixed version installs an older version from when it was still supported.

There's a separate `environment-mac.yml` file included as well, although we haven't tested it on any non-Apple Silicon macs. However, due to what seems to be an issue with `torchaudio` in the `pytorch-nightly` channel, the environment file [suddenly stopped working yesterday](https://github.com/sudosilico/sample-diffusion/issues/7). Unfortunately, it looks like we have to wait for this to be resolved in `pytorch-nightly`.

**Comment by ediooo** [comment]
Thanks a lot for the info! I just installed it successfully using the environment-mac.yml on my Intel Mac Pro (2019) and generated some sounds using my model. No issues. Appreciate this tool a lot :) 

**Oh and: How can I set the length of the output WAV file that generate.py produces? I currently only get 1.3 seconds. I'd like 40 seconds...**

**Comment by sudosilico** [comment]
> **Oh and: How can I set the length of the output WAV file that generate.py produces? I currently only get 1.3 seconds. I'd like 40 seconds...**

Currently there's no "proper" way to generate samples longer than the chunk size that the model was trained on. There's a slight "hack" that you can achieve by doing a variation of an audio file with the length that you want (i.e. passing one .wav for `--input`), but with a noise_level of `1.0`, so that none of the input signal will be present in the generation, but this usually doesn't sound the best. Inpainting is one of the things we're currently looking into to solve this problem in a better way, but we can't give an ETA for it at the moment. Although if it makes its way into the Harmonai notebooks before we can manage it, we'll definitely port it over.

**Comment by ediooo** [comment]
Trying this now, thanks! 

To make it longer I would also have to set --length_multiplier to 5 or something, right?
By default it would output the length of 1 chunk size only?
